 
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm build
branches:
    - master
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: nareshr.s3.amazonaws.com
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # Path to a directory containing your built site.
  local_dir: website/build
  cache_control: "max-age=21600"
